services:
  p-postgres:
    image: postgres:16-alpine

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_DB: ${POSTGRES_DB:-db}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - shared-network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  shared-network:
    name: shared-network
    external: true
